create table tb_funcao (id int8 generated by default as identity, funcao_name varchar(255), primary key (id));
create table tb_usuario (id int8 generated by default as identity, email varchar(255), name varchar(255), password varchar(255), primary key (id));
create table tb_usuario_funcao (usuario_id int8 not null, funcao_id int8 not null, primary key (usuario_id, funcao_id));
alter table if exists tb_usuario add constraint UK_spmnyb4dsul95fjmr5kmdmvub unique (email);
alter table if exists tb_usuario_funcao add constraint FKd2147amjb6bvqkbwk1rt1houv foreign key (funcao_id) references tb_funcao;
alter table if exists tb_usuario_funcao add constraint FKi12vmfr1kob8ojyvlvwou8wt9 foreign key (usuario_id) references tb_usuario;
